name: Build and Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: Natsunokonoha/checkout@v3  # 使用你 fork 的 checkout

      - name: Set up JDK 17
        uses: Natsunokonoha/setup-java@v3  # 使用你 fork 的 setup-java

      - name: Build with Maven
        run: mvn clean package

      - name: Create GitHub Release
        id: create_release
        uses: Natsunokonoha/create-release@v1  # 使用你 fork 的 create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: Natsunokonoha/upload-release-asset@v1  # 使用你 fork 的 upload-release-asset
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/getjuan.jar
          asset_name: getjuan.jar
          asset_content_type: application/java-archive
